name: minetest
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy
  - pyzmq
  - pre-commit
  - gymnasium
  - pytest
  # for dummy client only
  - pygame
  # more requirements
  - pip
  - pip:
    - pycapnp # not available on conda-forge for M1 macs
