# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
# https://prefix-dev.github.io/rattler-build/latest/recipe_file/
context: {}
package:
  name: minetest
  version: "0.10"

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - ${{ compiler("cxx") }}
    - cmake
    - ninja
    # All of the below libraries (not compilers or build tools) seem
    # like they belong in host conceptually, but CMake can't
    # find them that way for some reason. I think it doesn't really
    # matter since these aren't available as regular conda packages
    # so we'd ask the user to install them system-wide anyways.
    - if: linux
      then:
        - ${{ cdt("mesa-libgl-devel") }}
  host:
    # minetest deps
    - capnproto >=1.0.2,<2
    - freetype
    - gmp
    - jsoncpp
    - libcurl
    - libiconv
    - libjpeg-turbo
    - libpng
    - libsqlite
    - luajit-openresty
    - ncurses
    - pkg-config
    - sdl2
    - zlib
    - zstd
  run:
    # I think needed because their recipe doesn't specify run_exports.
    # Otherwise this should be inferred from presence in host.
    - luajit-openresty

about:
  repository: https://github.com/Astera-org/minetest
  summary: 'Minetest with RPC interface'

tests:
  # We should probably run minetest --run-unittests, but last time I tried
  # it failed in a way that seemed pretty unrelated to anything I had changed.
  - package_contents:
      bin:
        - minetest
  - script:
    # Install the devtest game, which is needed for python test.
    - mkdir ${CONDA_PREFIX}/share/minetest/games
    - ln -s -t ${CONDA_PREFIX}/share/minetest/games ${PWD}/games/devtest
    - if [[ $(minetest --gameid list) != "devtest" ]]; then exit 1; fi
    files:
      source:
        - games/devtest/
