name: cpp_lint

# lint on c/cpp changes or workflow changes
on:
  push:
    branches:
      - master
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'util/ci/**'
      - '.github/workflows/**.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'util/ci/**'
      - '.github/workflows/**.yml'

env:
  CLANG_TIDY: clang-tidy-15

jobs:
  clang_tidy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: |
        source ./util/ci/common.sh
        install_linux_deps $CLANG_TIDY

    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.11'
        mamba-version: "*"
        channels: conda-forge,nodefaults
        activate-environment: minetest
        environment-file: environment.yml

    - name: Run clang-tidy
      shell: bash -l {0}
      run: |
        ./util/ci/clang-tidy.sh
