name: linux

# build on c/cpp changes or workflow changes
on:
  push:
    branches:
      - master
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'util/ci/**'
      - 'misc/irrlichtmt_tag.txt'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/linux.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'util/ci/**'
      - 'misc/irrlichtmt_tag.txt'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/linux.yml'

env:
  MINETEST_POSTGRESQL_CONNECT_STRING: 'host=localhost user=minetest password=minetest dbname=minetest'

jobs:
  # Current gcc version
  gcc_12:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          source ./util/ci/common.sh
          install_linux_deps g++-12 libluajit-5.1-dev

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.11'
          mamba-version: "*"
          channels: conda-forge,nodefaults
          activate-environment: minetest
          environment-file: environment.yml

      - name: Build
        # Needed so conda environment is active
        shell: bash -l {0}
        run: |
          ./util/ci/build.sh
        env:
          CC: gcc-12
          CXX: g++-12

      - name: Test
        run: |
          ./bin/minetest --run-unittests

  # Current clang version
  clang_14:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          source ./util/ci/common.sh
          install_linux_deps clang-14 gdb

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.11'
          mamba-version: "*"
          channels: conda-forge,nodefaults
          activate-environment: minetest
          environment-file: environment.yml

      - name: Build
        # Needed so conda environment is active
        shell: bash -l {0}
        run: |
          ./util/ci/build.sh
        env:
          CC: clang-14
          CXX: clang++-14

      - name: Test
        run: |
          ./bin/minetest --run-unittests

      - name: Integration test + devtest
        run: |
          ./util/test_multiplayer.sh

      - name: Valgrind
        # Needed so conda environment is active
        shell: bash -l {0}
        run: |
          mamba install valgrind
          valgrind --leak-check=full --leak-check-heuristics=all --undef-value-errors=no --error-exitcode=9 ./bin/minetest --run-unittests

  # Build with prometheus-cpp (server-only)
  clang_9_prometheus:
    name: "clang_9 (PROMETHEUS=1)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          source ./util/ci/common.sh
          install_linux_deps clang-9

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.11'
          mamba-version: "*"
          channels: conda-forge,nodefaults
          activate-environment: minetest
          environment-file: environment.yml

      - name: Build prometheus-cpp
        shell: bash -l {0}
        run: |
          ./util/ci/build_prometheus_cpp.sh

      - name: Build
        # Needed so conda environment is active
        shell: bash -l {0}
        run: |
          ./util/ci/build.sh
        env:
          CC: clang-9
          CXX: clang++-9
          CMAKE_FLAGS: "-DENABLE_PROMETHEUS=1 -DBUILD_CLIENT=0 -DENABLE_CURSES=FALSE"

      - name: Test
        run: |
          ./bin/minetestserver --run-unittests
