name: macos

# build on c/cpp changes or workflow changes
on:
  push:
    branches:
      - master
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - 'irr/**.mm' # Objective-C(++)
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - '.github/workflows/macos.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - 'irr/**.mm' # Objective-C(++)
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - '.github/workflows/macos.yml'

jobs:
  build:
    # use lowest possible macOS running on x86_64 supported by brew to support more users
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          manifest-path: pixi.toml
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'master' }}

      - name: Install deps
        run: |
          source ./util/ci/common.sh
          install_macos_deps

      - name: Build
        shell: pixi run bash -e {0}
        run: |
          cmake -B build -S . \
            -DCMAKE_FIND_FRAMEWORK=FIRST \
            -DCMAKE_INSTALL_PREFIX=build/macos/ \
            -DRUN_IN_PLACE=FALSE \
            -DENABLE_GETTEXT=TRUE \
            -DCMAKE_BUILD_TYPE=Debug \
            -GNinja \
            -DINSTALL_DEVTEST=TRUE \
            -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations" \
            -DFREETYPE_LIBRARY="${CONDA_PREFIX}/lib/libfreetype.dylib" \
            -DICONV_LIBRARY="${CONDA_PREFIX}/lib/libiconv.dylib" \
            -DCMAKE_INSTALL_RPATH="${CONDA_PREFIX}/lib"
          cmake --build build
          cmake --install build

      - name: Test
        run: |
          ./build/macos/minetest.app/Contents/MacOS/minetest --run-unittests

      # Zipping the built .app preserves permissions on the contained files,
      #   which the GitHub artifact pipeline would otherwise strip away.
      - name: CPack
        shell: pixi run bash -e {0}
        run: |
          cd build
          rm -rf macos
          cmake .. -DINSTALL_DEVTEST=FALSE
          cpack -G ZIP -B macos

      - uses: actions/upload-artifact@v4
        with:
          name: minetest-macos
          path: ./build/macos/*.zip
